# Generated by Django 5.0 on 2024-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_email_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.TimeField(null=True),
        ),
    ]
