# Generated by Django 5.0 on 2024-06-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_pace', models.FloatField(null=True)),
                ('voice_variation', models.FloatField(null=True)),
                ('pausing', models.FloatField(null=True)),
                ('filler_words', models.FloatField(null=True)),
                ('grammar', models.FloatField(null=True)),
                ('language_variation', models.FloatField(null=True)),
                ('script', models.FloatField(null=True)),
                ('eye_contact_head_gaze', models.FloatField(null=True)),
                ('gesture_use', models.FloatField(null=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.file')),
            ],
        ),
    ]
