# Generated by Django 5.0 on 2024-07-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
