# Generated by Django 5.0.7 on 2024-08-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_performancemetrics_eye_contact_head_gaze_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancemetrics",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customer",
            ),
        ),
        migrations.AlterField(
            model_name="performancemetrics",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.file",
            ),
        ),
    ]
