List<String> job_titles = [
    "public speaker",
    "teacher",
    "professor",
    "student",
    "business executive",
    "politician",
    "actor/actress",
    "lawyer",
    "journalist",
    "corporate trainer",
    "consultant",
    "motivational speaker",
    "customer service representative",
    "marketing professional",
    "human resources manager",
    "streamer",
    "nonprofit organizer",
    "entrepreneur",
    "community leader",
    "media personality",
    "social worker",
    "coach/instructor",
    "project manager",
];
